workloads:
  admin:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-frontend.git
    image: docker.io/scgskku/alumni-admin-fe-prod
    branches:
      testing: develop
      production: main
    port: 3000
    readiness:
      type: tcp

domain:
  name: admin.alumni.scg.skku.ac.kr
  external: false

routes:
  - path: /
    workload: admin
