# Engineering 1 Server node specific patches
apiVersion: v1alpha1
kind: HostnameConfig
hostname: k8s.e1s
auto: off
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 8.8.8.8
  - address: 8.8.4.4
---
machine:
  install:
    diskSelector:
      wwid: REPLACE_WITH_E1S_SYSTEM_DISK_WWID
