# Engineering 1 Server node specific patches
machine:
  install:
    diskSelector:
      wwid: REPLACE_WITH_E1S_SYSTEM_DISK_WWID
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: k8s.e1s
auto: off
