# Engineering 2 Server node specific patches
apiVersion: v1alpha1
kind: HostnameConfig
hostname: k8s.e2s
auto: off
---
machine:
  install:
    diskSelector:
      wwid: REPLACE_WITH_E2S_SYSTEM_DISK_WWID
