# Engineering 2 Server node specific patches
apiVersion: v1alpha1
kind: HostnameConfig
hostname: e2s.k8s
auto: off
---
machine:
  install:
    diskSelector:
      wwid: naa.61418770621bbc00321ac43f2b9a04af
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: data
provisioning:
  diskSelector:
    match: disk.wwid == "naa.61418770621bbc00321acff30706c889"
  minSize: 1TB
  grow: true
