apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-releases
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/SystemConsultantGroup/kubernetes.git
        revision: main
        files:
          - path: applications/*/releases/production.yaml
          - path: applications/*/releases/testing.yaml
  template:
    metadata:
      name: 'app-{{ trimSuffix ".yaml" .path.filename }}-{{ index .path.segments 1 }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: applications
      sources:
        - repoURL: https://github.com/SystemConsultantGroup/kubernetes.git
          targetRevision: main
          path: argocd/charts/application
          helm:
            releaseName: 'app-{{ trimSuffix ".yaml" .path.filename }}-{{ index .path.segments 1 }}'
            valueFiles:
              - '$values/applications/{{ index .path.segments 1 }}/meta.yaml'
              - '$values/{{ .path.path }}/{{ .path.filename }}'
            values: |
              _context:
                application: '{{ index .path.segments 1 }}'
                release:
                  type: '{{ trimSuffix ".yaml" .path.filename }}'
        - repoURL: https://github.com/SystemConsultantGroup/kubernetes.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: 'app-{{ trimSuffix ".yaml" .path.filename }}-{{ index .path.segments 1 }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            gateway.scg.sh/public: "true"
            platform.scg.sh/application: '{{ index .path.segments 1 }}'
            platform.scg.sh/release: '{{ trimSuffix ".yaml" .path.filename }}'
            pod-security.kubernetes.io/enforce: restricted
            pod-security.kubernetes.io/enforce-version: latest
        syncOptions:
          - CreateNamespace=true
