apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Prune=false
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://percona.github.io/percona-helm-charts/
      chart: pxc-operator
      targetRevision: 1.20.0
      helm:
        releaseName: percona-operator
        valueFiles:
          - $values/argocd/platform/percona-operator/values.yaml
    - repoURL: https://github.com/SystemConsultantGroup/kubernetes.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
