user:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-frontend.git
    revision: 58cba2ea4acbb33daf6dc5b82a9776251ad74e60
  image: ghcr.io/systemconsultantgroup/alumni-platform-user@sha256:64030af611581cf7b256b3a8133f1c84dc95f110c2c47e6f47e26d732f64746d
admin:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-frontend.git
    revision: 58cba2ea4acbb33daf6dc5b82a9776251ad74e60
  image: ghcr.io/systemconsultantgroup/alumni-platform-admin@sha256:1892700e41796c02e052f3236fb8ad6b2f1e9674e8adcf978b4fee8866f2ba28
be:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-backend.git
    revision: ca7fc4d4c9d5c9a032adb2ee0d574df81f25c123
  image: ghcr.io/systemconsultantgroup/alumni-platform-be@sha256:e8713c191ea161fe09b8257cbb1d52dcfc6f82750300294942c8ae03e2bdd88d
