user:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-frontend.git
    revision: 58cba2ea4acbb33daf6dc5b82a9776251ad74e60
  image: ghcr.io/systemconsultantgroup/alumni-platform-user@sha256:64030af611581cf7b256b3a8133f1c84dc95f110c2c47e6f47e26d732f64746d
admin:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-frontend.git
    revision: 58cba2ea4acbb33daf6dc5b82a9776251ad74e60
  image: ghcr.io/systemconsultantgroup/alumni-platform-admin@sha256:1892700e41796c02e052f3236fb8ad6b2f1e9674e8adcf978b4fee8866f2ba28
be:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-backend.git
    revision: fcc0556b4768d2797f348a1da4da63034f004ad3
  image: ghcr.io/systemconsultantgroup/alumni-platform-be@sha256:962f6341b472b02a9d185e79372310503040b46d8138912fbba77f1c6fba6c67
