user:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-frontend.git
    revision: 58cba2ea4acbb33daf6dc5b82a9776251ad74e60
  image: ghcr.io/systemconsultantgroup/alumni-platform-user@sha256:64030af611581cf7b256b3a8133f1c84dc95f110c2c47e6f47e26d732f64746d
admin:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-frontend.git
    revision: 58cba2ea4acbb33daf6dc5b82a9776251ad74e60
  image: ghcr.io/systemconsultantgroup/alumni-platform-admin@sha256:1892700e41796c02e052f3236fb8ad6b2f1e9674e8adcf978b4fee8866f2ba28
be:
  source:
    repository: https://github.com/SystemConsultantGroup/skku-alumni-backend.git
    revision: e2ca350294b1b0aa412d6f727ff236f75cbcba3b
  image: ghcr.io/systemconsultantgroup/alumni-platform-be@sha256:17f0220c1c71b9a4fe1cdbb652360e5e125b66b3791338463b832874174726d3
