workloads:
  be:
    repository: https://github.com/SystemConsultantGroup/exhibition-backend.git
    image: docker.io/scgskku/exhibition-be
    branches:
      production: main
    port: 8080
    env:
      from:
        secrets:
          - exhibition-be-secret

domain:
  name: api.exhibition.scg.sh
  external: false

routes: custom
