workloads:
  web:
    repository: https://github.com/SystemConsultantGroup/timetable-planner-frontend.git
    image: docker.io/scgskku/timetable-planner-fe-prod
    branches:
      testing: dev
      production: main
    port: 3000

domain:
  name: skkedule.scg.skku.ac.kr
  external: false

routes:
  - path: /
    workload: web
