apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: 1.20.0
      helm:
        releaseName: cilium
        valueFiles:
          - $values/argocd/platform/cilium/values.yaml
    - repoURL: https://github.com/SystemConsultantGroup/kubernetes.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
