apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
  namespace: gateway-system
spec:
  gatewayClassName: cilium
  allowedListeners:
    namespaces:
      from: Selector
      selector:
        matchLabels:
          gateway.scg.sh/public: "true"
  listeners:
    - name: platform-https
      hostname: "*.platform.scg.sh"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: platform-wildcard-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.scg.sh/public: "true"
    - name: testing-https
      hostname: "*.testing.scg.sh"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: application-wildcards-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.scg.sh/public: "true"
    - name: preview-https
      hostname: "*.preview.scg.sh"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: application-wildcards-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.scg.sh/public: "true"
