# Supplied by the generated Argo CD Application.
_context:
  htmlInjector:
    wasm:
      url: https://raw.githubusercontent.com/SystemConsultantGroup/kubernetes/main/argocd/charts/application/files/envoy_html_injector.wasm
      sha256: 35efa0c57e1a91fd7f00b66485d08cf433b6e4a13858ce46e7b84bd8fc2dcd34
