workloads:
  be:
    repository: https://github.com/SystemConsultantGroup/room-reservation-backend.git
    image: docker.io/scgskku/reservation-be-prod
    branches:
      testing: develop
      production: main
    port: 8000
    readiness:
      type: tcp
    env:
      from:
        secrets:
          - reservation-secret

domain:
  name: api.reservation.scg.skku.ac.kr
  external: false

routes:
  - path: /
    workload: be
