workloads:
  pdf:
    repository: https://github.com/SystemConsultantGroup/PDF-Converter-Module.git
    image: docker.io/jcy0308/pdf-module
    branches:
      production: main
    port: 4000
    replicas:
      production: 1
    resources:
      requests:
        cpu: "2"
        memory: 3Gi
      limits:
        cpu: "2"
        memory: 4Gi
    env:
      from:
        secrets:
          - pdf-secret
