apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    email: scg@scg.skku.ac.kr
    server: https://acme.zerossl.com/v2/DV90
    privateKeySecretRef:
      name: zerossl-cloudflare-account
    externalAccountBinding:
      keyID: y3xGHKQKa3p96B6gdKwhXQ
      keySecretRef:
        name: zerossl-eab
        key: hmac-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
