apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuer.yaml
  - argocd-certificate.yaml
  - platform-wildcard-certificate.yaml
  - application-wildcard-certificate.yaml
