apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform.yaml
  - projects/applications.yaml
  - application-sets/releases.yaml
  - application-sets/previews.yaml
  - application-sets/kustomize.yaml
  - platform/argocd/application.yaml
  - platform/cert-manager/application.yaml
  - platform/external-dns-scg.sh/application.yaml
  - platform/gateway/application.yaml
