apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform.yaml
  - projects/applications.yaml
  - application-sets/instances.yaml
  - application-sets/kustomize.yaml
  - platform/argocd/application.yaml
  - platform/gateway-api/application.yaml
  - platform/cilium/application.yaml
  - platform/cert-manager/application.yaml
  - platform/external-dns-scg.sh/application.yaml
  - platform/external-secrets/application.yaml
  - platform/gateway/application.yaml
  - platform/local-path-provisioner/application.yaml
  - platform/percona-operator/application.yaml
  - platform/mysql/application.yaml
  - platform/reloader/application.yaml
  - platform/vault/application.yaml
