global:
  domain: argocd.platform.scg.sh
configs:
  params:
    server.insecure: true
  cm:
    url: https://argocd.platform.scg.sh
    webhook.maxPayloadSizeMB: "10"
    timeout.reconciliation: 120s
    timeout.reconciliation.jitter: 60s
    admin.enabled: false
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23liOiPk0ECCc9Wfgk
            clientSecret: $argocd-github-oauth:github.oauth.clientSecret
            orgs:
              - name: SystemConsultantGroup
                teams:
                  - active
            teamNameField: slug
  secret:
    githubSecret: '$argocd-github-webhook:webhook.github.secret'
  rbac:
    policy.csv: |
      g, SystemConsultantGroup:active, role:readonly
    policy.default: role:readonly
    scopes: '[groups]'
applicationSet:
  httproute:
    enabled: true
    parentRefs:
      - name: public
        namespace: gateway-system
        sectionName: platform-https
    hostnames:
      - argocd.platform.scg.sh
    rules:
      - matches:
          - path:
              type: Exact
              value: /applicationset-webhook
        filters:
          - type: URLRewrite
            urlRewrite:
              path:
                type: ReplaceFullPath
                replaceFullPath: /api/webhook
