apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-backup-vault-auth
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: mysql-backups
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    vault:
      server: https://vault.platform.scg.sh
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: mysql-backups
          serviceAccountRef:
            name: mysql-backup-vault-auth
            audiences:
              - vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-backup-s3
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: mysql-backups
  target:
    name: mysql-backup-s3
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: platform/mysql/s3
        property: MINIO_ACCESS_KEY
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: platform/mysql/s3
        property: MINIO_SECRET_KEY
