apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: mysql
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  finalizers:
    - percona.com/delete-pxc-pods-in-order
spec:
  crVersion: 1.20.0
  secretsName: pxc-system-users
  tls:
    enabled: true
  unsafeFlags:
    pxcSize: true
    proxySize: true
  updateStrategy: RollingUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 2
    image: percona/percona-xtradb-cluster:8.0.45-36.1
    autoRecovery: true
    configuration: |
      [mysqld]
      character_set_server=utf8mb4
      collation_server=utf8mb4_general_ci
      default_time_zone=+09:00
      innodb_buffer_pool_size=12G
      innodb_flush_log_at_trx_commit=1
      lower_case_table_names=0
      max_connections=500
      pxc_strict_mode=ENFORCING
      skip_name_resolve=ON
      sync_binlog=1
    resources:
      requests:
        cpu: "4"
        memory: 16Gi
      limits:
        cpu: "16"
        memory: 24Gi
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: local-data
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 250Gi
    gracePeriod: 600
  haproxy:
    enabled: true
    size: 2
    image: percona/haproxy:2.8.18-1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  proxysql:
    enabled: false
  logcollector:
    enabled: true
    image: percona/fluentbit:5.0.6-1
    resources:
      requests:
        cpu: 200m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 256Mi
  pmm:
    enabled: false
    image: percona/pmm-client:3.8.0
    serverHost: monitoring-service
  backup:
    image: percona/percona-xtrabackup:8.0.35-35.1
    pitr:
      enabled: false
