apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: mysql
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: mysql
spec:
  provider:
    vault:
      server: https://vault.platform.scg.sh
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: mysql
          serviceAccountRef:
            name: vault-auth
            audiences:
              - vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pxc-system-users
  namespace: mysql
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: pxc-system-users
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: platform/mysql/pxc-system-users
