fe:
  source:
    repository: https://github.com/SystemConsultantGroup/kubernetes-example.git
    revision: "66402e5a485a67b40f0decc2d13cc19a21ba7f67"
  image: ghcr.io/systemconsultantgroup/kubernetes-example@sha256:440426c4b26f954622f99df7da5567abd4ad9efb5ff6d1e96be36c7db0ccab8a
