name: external-dns-scg.sh
namespace: external-dns
source:
  type: helm
  repoURL: https://kubernetes-sigs.github.io/external-dns/
  chart: external-dns
  targetRevision: 1.21.1
  values: argocd/platform/external-dns-scg.sh/values.yaml
