fullnameOverride: external-dns-scg-sh
provider:
  name: cloudflare
sources:
  - gateway-httproute
gatewayNamespace: gateway-system
domainFilters:
  - scg.sh
policy: sync
registry: txt
txtOwnerId: scg.sh
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token
