schema-version = "1.14.0"

[install]
age.pkg-path = "age"
cilium-cli.pkg-path = "cilium-cli"
kubectl.pkg-path = "kubectl"
kubernetes-helm.pkg-path = "kubernetes-helm"
sops.pkg-path = "sops"
talosctl.pkg-path = "talosctl"
yq-go.pkg-path = "yq-go"

[hook]
on-activate = '''
  export PATH="$FLOX_ENV_PROJECT/scripts:$PATH"
  export TALOSCONFIG="$FLOX_ENV_PROJECT/talosconfig"
  export KUBECONFIG="$FLOX_ENV_PROJECT/kubeconfig"
'''

[profile]
bash = '''
  source "$FLOX_ENV_PROJECT/scripts/completions/t.bash"
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
