workloads:
  api:
    repository: https://github.com/SystemConsultantGroup/timetable-planner-backend.git
    image: docker.io/scgskku/timetable-planner-be-prod
    branches:
      testing: dev
      production: main
    port: 8080
    env:
      from:
        secrets:
          - timetable-planner-be-secret

domain:
  name: api.skkedule.scg.skku.ac.kr
  external: false

routes:
  - path: /
    workload: api
