global:
  tlsDisable: false
injector:
  enabled: false
server:
  volumes:
    - name: vault-server-tls
      secret:
        secretName: vault-server-tls
  volumeMounts:
    - name: vault-server-tls
      mountPath: /vault/userconfig/vault-server-tls
      readOnly: true
  extraSecretEnvironmentVars:
    - envName: VAULT_TRANSIT_SEAL_TOKEN
      secretName: vault-transit-seal
      secretKey: token
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: local-data
  auditStorage:
    enabled: true
    size: 10Gi
    storageClass: local-data
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 1
    apiAddr: https://vault.platform.scg.sh
    raft:
      enabled: true
      setNodeId: true
      config: |-
        ui = true

        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
          tls_key_file = "/vault/userconfig/vault-server-tls/tls.key"
        }

        storage "raft" {
          path = "/vault/data"
        }

        seal "transit" {
          address = "https://kms.vault.platform.scg.sh"
          token = "env://VAULT_TRANSIT_SEAL_TOKEN"
          disable_renewal = "true"
          mount_path = "transit"
          key_name = "vault-root"
        }

        service_registration "kubernetes" {}
ui:
  enabled: true
csi:
  enabled: false
