apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - route.yaml
configMapGenerator:
  - name: monitoring-grafana-node-overview
    files:
      - node-overview.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
