apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 7.3.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/argocd/platform/loki/values.yaml
    - repoURL: https://github.com/SystemConsultantGroup/kubernetes.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/SystemConsultantGroup/kubernetes.git
      targetRevision: main
      path: argocd/platform/loki/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
