manager:
  source:
    repository: https://github.com/SystemConsultantGroup/exhibition-manage.git
    revision: "e36795b9ef0b4938d6249f6006fecaeda3ce09e8"
  image: ghcr.io/systemconsultantgroup/exhibition-manage@sha256:a79ed48bf6f14f849efb220ca999851d96542de731723faaf4bad5e24fd063d4
