manager:
  source:
    repository: https://github.com/SystemConsultantGroup/exhibition-manage.git
    revision: "76161f4e03605737ee4eac5b9a1c4e549dddb5ad"
  image: ghcr.io/systemconsultantgroup/exhibition-manage@sha256:afa4e995f11a589329fce0b7948bab142805ed6d37e9cd0c9f9448b3e41666ac
